---
title: "Lab 6 Grading Guide"
format: html
embed-resources: true
editor: visual
---

| Learning Objective           | Mastery                                                                                                                    | Proficient                                                                                                                                    | Novice                                                                                                         |
|------------------------------|----------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| DM-3: APIs                   | I could use help here!                                                                                                     | I could use help here!                                                                                                                        | I could use help here!                                                                                         |
| DM-2: Iteration              | `map()` or `apply()` functions are used for every iteration                                                                | Some iterations use `for()` loops while others use `map()` and / or `apply()` functions                                                       | Every iteration is done using a `for()` loop                                                                   |
| DM-1: Data Cleaning          | Numerous changes are made to variables with poor formatting to make them simple to interpret (e.g., May 1, 2024 at 2:51pm) | Slight changes are made to variables with poor formatting to make them easier to interpret (e.g., 2024-05-01 14:51:03)                        | Few if any changes are made to variables with poor formatting                                                  |
| CD-3: Helper Functions       | Helper functions are used consistently — helper functions are used for every complex process (requiring multiple steps)    | Helper functions are used sporadically — some steps are broken out into smaller functions, but others are left in the body of large functions | Functions are not deconstructed into parts — few if any helper functions are used                              |
| CD-1: Vectorized Functions   | Vectorization is used consistently — every function uses it                                                                | Vectorization is used sporadically — some functions use it and some don't                                                                     | Vectorization is not used when writing functions                                                               |
| CD-2: Intermediate Objects   | Immaculate R workspace – intermediate objects are not used unless absolutely necessary                                     | Mostly clean R workspace – intermediate objects are [occasionally]{.underline} used when they are not needed                                  | Cluttered R workspace – intermediate objects are [frequently]{.underline} used when they are not needed        |
| TC-2: Function Documentation | Comments guide the reader through each step of the function                                                                | Comments guide the reader through the "major" parts of the function                                                                           | Few if any comments are used in the body of the function to guide the reader through the process being enacted |
| PV-3: leaflet                | Proficient + tailors map visualizations                                                                                    | Uses mapping for data visualizations but largely relies on default characteristics                                                            |                                                                                                                |
| RW-2: Quarto Document        | Proficient + uses YAML options to tailor the format of the HTML file                                                       | Uses many code chunk options to tailor the format of the rendered HTML, no messages or warnings are output                                    | Code is shown in the rendered document, but messages and warnings being output on the page                     |
