---
title: "Lab 2 Grading Guide"
format: html
embed-resources: true
editor: visual
---

| Learning Objective                                                | Mastery                                                                                                                         | Proficient                                                                                                              | Novice                                                                                                                    |
|------------------------------|--------------|--------------|--------------|
| PV-1: Less Common Geometries                                      | Proficient + multiple geometries                                                                                                | Uses at least one geometry that is less common                                                                          | No evidence of using less common geometries                                                                               |
| PV-1: Map Variables                                               | Proficient + tailors map visualizations                                                                                         | Uses mapping for data visualizations but largely relies on default characteristics                                      | No evidence of using mapping for data visualizations                                                                      |
| PV-1: Annotations                                                 | Proficient + tailors the size, color, font of the annotations                                                                   | Novice + includes annotations in multiple locations                                                                     | Can add simple annotations to visualization                                                                               |
| PV-2: Titles, Subtitles, Axis Labels                              | Proficient + tailors labels to remove legend                                                                                    | Novice + labels don't make people tilt their head                                                                       | Plot labels are descriptive and include units, but make people tilt their head                                            |
| PV-2: Colors                                                      | Proficient + tailors ordering of colors, saturation of colors to make the plot more clear                                       | Uses an R package to tailor colors                                                                                      | Uses default ggplot colors                                                                                                |
| PV-2: Themes                                                      | Proficient + uses additional theme options (e.g., grid lines, font size)                                                        | Uses built-in themes (e.g., `theme_bw()` to tailor plots                                                                | Uses default ggplot theme                                                                                                 |
| PV-3: gganimate                                                   | Proficient + more complex transitions are used                                                                                  | gganimate is used to integrate transition states                                                                        | No evidence of using gganimate                                                                                            |
| PV-3: Interactive Plots                                           | Proficient + interactive elements include multiple features of the data (e.g., including information on observations via hover) | R packages are used to create interactive plots with simple features exploring the data (e.g., names of observations)   | No evidence of using interactive plots                                                                                    |
| RW-1: Load Data with `here`                                       | Uses `here()` to read in data from subfolder within main folder                                                                 | Uses `here()` to read in data from main folder                                                                          | Does not use `here()` to load in data                                                                                     |
| RW-1: Organized scripts, data, notebooks                          | Subfolders are used to organize files, and files are given informative names that describe their contents                       | All files are included in main repo (no subfolders), but files are given informative names that describe their contents | All files are included in main repo (no subfolders), names of files are not informative (do not describe their contents)  |
| RW-2: Polished rendered document & appropriate code chunk options | Proficient + uses YAML options to tailor the format of the HTML file                                                            | Uses many code chunk options to tailor the format of the rendered HTML, no messages or warnings are output              | Code is shown in the rendered document, but messages and warnings being output on the page                                |
| RW-3: Clear, readable, well commented code                        | Proficient + additional formatting (e.g., extra new lines) is used to make the code more readable                               | In all but a few instances the code adheres to tidyverse style guide                                                    | At times, the code adheres to the tidyverse style guide, but often it does not                                            |
| CD-2: Saving Intermediate Objects                                 | Immaculate R workspace – intermediate objects are not used unless absolutely necessary                                          | Mostly clean R workspace – intermediate objects are [occasionally]{.underline} used when they are not needed            | Cluttered R workspace – intermediate objects are [frequently]{.underline} used when they are not needed                   |
